# Generated by Django 2.1.2 on 2021-01-08 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activada/ Categoria no Activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion ')),
            ],
        ),
        migrations.CreateModel(
            name='Censo_Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12)),
                ('cedula', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('numero_de_casa', models.IntegerField()),
                ('cantidad_de_habitantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='coment_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Nombre_de_calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_calle_persona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.SlugField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('imagen', models.ImageField(upload_to='post/photos')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('autor_de_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphelp.Categoria')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coment_post',
            name='Post_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphelp.Post'),
        ),
        migrations.AddField(
            model_name='coment_post',
            name='autor_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='censo_servicios',
            name='nombre_de_calle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphelp.Nombre_de_calle'),
        ),
        migrations.AddField(
            model_name='censo_servicios',
            name='servicio',
            field=models.ManyToManyField(to='apphelp.Servicios'),
        ),
    ]
