# Generated by Django 2.1.2 on 2021-01-15 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apphelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporte_generado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('Pago', models.BooleanField(default=False, verbose_name='Pago realizado/Pago No realizado')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphelp.Censo_Servicios')),
                ('servicio_seleccionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphelp.Servicios')),
            ],
        ),
    ]
